---
title: "Exploring growth rates IWYP"
author: "A Bowerman, D Ganguly"
date: "21/05/2019"
output: html_document
---

### Aim 
Explore growth rates across IWYP field trial data.

### Method

Utilise measures of Normalized Vegetation Index (NDVI, Greenseeker) to estimate growth rates using a nonlinear modelling approach [Paine et al 2012](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/j.2041-210X.2011.00155.x). Also see [Fitting von Bertalanffy Growth Function](http://rpubs.com/lacs/1123).

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, tidy = TRUE, warning = FALSE, message = FALSE, results = 'asis')

library(tidyverse)
library(DBI) ## functions to interface with databases
library(RMySQL) ## database implementation
library(rstudioapi)
library(janitor)

## generate DBI COnnection Object / establish connection with database
con <- dbConnect(MySQL(),
          dbname="iwyp60_germinate_dev",
          user = "iwyp60ro",
          host = 'wheatyield.anu.edu.au')

## read tables required to pull database info
table_names <- dbListTables(con)
rq_tables <- c("phenotypedata", "phenotypes","datasetmembers", "datasets", "experiments", "germinatebase")
tables <- lapply(FUN=dbReadTable, X=rq_tables, conn=con)
names(tables) <- rq_tables

df <- select(tables$phenotypedata, phenotype_id, germinatebase_id, dataset_id, phenotype_value) %>%
  full_join(., tables$phenotypes, by=c("phenotype_id"="id")) %>%
  full_join(., tables$germinatebase, by=c("germinatebase_id"="id")) %>%
  full_join(., tables$datasets, by=c("dataset_id"="id")) %>%
  select(-breeders_code, -breeders_name, -subtaxa_id, -puid, -colldate, -collcode, -collname, -collmissid, -othernumb, -duplsite, -duplinstname)

## disconnect from database
dbDisconnect(con)

```

### Results

```{r}
## get phenotype IDs of interest
keep_ids <- filter(tables$phenotypes, sapply(strsplit(short_name,";"), function(l) l[1]) == "NDVI") %>% select(id)

## subset global df to NDVI values
a <- filter(df, phenotype_id %in% keep_ids) %>% select(phenotype_id, germinatebase_id, experiment_id, dataset_id, description.y, phenotype_value)


```

